### ISSUE TITLE
DPL-987 - As developers we need to modify library so it can have it's own tube so a library can exist in its own right without belonging to a pool

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#1151]
**User story**
As developers we need to modify library so it can have it's own tube so a library can exist in it's own right without belonging to a pool

**Who are the primary contacts for this story**
James / Steve

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] a library to have it's own tube (optional)
- [ ] any pool which has a single library to delegate tube to library

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #1137
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by BenTopping** [comment]
Wondering how this fits in with DPL-994 (https://github.com/sanger/traction-ui/issues/1420). Do we want to get rid of the pools with just one library and migrate the barcodes over to the library? Otherwise we would be left with phantom pools that just exist to delegate to library. If we do DPL-994 first we could do this so libraries can be attached to wells and we can get rid of these single plexed pools entirely. On the other hand this would affect sample sheet generation as we would be dealing with libraries in the wells as well as pools. Just something to think about.

**Comment by stevieing** [comment]
> Wondering how this fits in with DPL-994 ([sanger/traction-ui#1420](https://github.com/sanger/traction-ui/issues/1420)). Do we want to get rid of the pools with just one library and migrate the barcodes over to the library? Otherwise we would be left with phantom pools that just exist to delegate to library. If we do DPL-994 first we could do this so libraries can be attached to wells and we can get rid of these single plexed pools entirely. On the other hand this would affect sample sheet generation as we would be dealing with libraries in the wells as well as pools. Just something to think about.

I think I have covered that in other stories. There is a story to give library it's own barcode (DPL-987) and there is also a migration somewhere to turn pools of 1 into libraries (DPL-990)
