### ISSUE TITLE
Y24-457 - Barcode Plate B addition to Traction LIMS for PacBio

### ISSUE THREAD

**Issue by Stan1520** [sanger/traction-service#1487]
**User story**

As Craig, I would like a new tag set for new barcode plates A, B, C and D so I can add tags to the pipeline.

**Primary Contacts**
- Craig Corton - chc@sanger.ac.uk
- James Watts - jw24@sanger.ac.uk

**Nominated testers for UAT**
- Craig Corton - chc@sanger.ac.uk
- James Watts - jw24@sanger.ac.uk

**Acceptance criteria** 
To be considered successful the solution must allow:
- [ ] The Pacbio_384_barcode_plates_ABCD tag set should be available
- [ ] The create tag set rake task should include the Pacbio_384_barcode_plates_ABCD tag set
- [ ] The tag set should be available in SMRT link (and available in UAT SMRTLink for testing - trac-smrtlink-uat.psd.sanger.ac.uk:8243/sl/data-management)
- [ ] The tag set should have the uuid. 6ed141f6-4293-d3ba-933e-0b9b60c8a7ce

**Additional context**
Attached is the file containing the barcode IDs and fasta sequences required

[SMRTbell_Barcoded_Adapter_Plates_ABCD_WSI.txt](https://github.com/user-attachments/files/17830919/SMRTbell_Barcoded_Adapter_Plates_ABCD_WSI.txt)

**Comment by stevieing** [comment]
Hi Stanley

There is nothing attached.

Steve.

From: Stan1520 ***@***.***>
Reply to: sanger/traction-service ***@***.***>
Date: Wednesday 20 November 2024 at 11:20
To: sanger/traction-service ***@***.***>
Cc: Stephen Inglis ***@***.***>, Mention ***@***.***>
Subject: [sanger/traction-service] Y24-457 - Barcode Plate B addition to Traction LIMS for PacBio (Issue #1487) [EXT]


User story

As Craig, I would like a new tag set for new barcode plates A, B, C and D so I can add tags to the pipeline.

Primary Contacts

  *   Craig Corton - ***@***.******@***.***>
  *   James Watts - ***@***.******@***.***>

Nominated testers for UAT

  *   Craig Corton - ***@***.******@***.***>
  *   James Watts - ***@***.******@***.***>

Acceptance criteria
To be considered successful the solution must allow:

  *   The Pacbio_384_barcode_plates_ABCD tag set should be available
  *   The create tag set rake task should include the Pacbio_384_barcode_plates_ABCD tag set
  *   The tag set should be available in SMRT link (and available in UAT SMRTLink for testing - trac-smrtlink-uat.psd.sanger.ac.uk:8243/sl/data-management)
  *   The tag set should have the uuid. 6ed141f6-4293-d3ba-933e-0b9b60c8a7ce

Additional context
Attached is the file containing the barcode IDs and fasta sequences required

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sanger_traction-2Dservice_issues_1487&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=xfd3i0lPw8VCmo8bCSyIgn49pfcfLF1wjuN7hntGNPMTIClhVBYJU6fbUsQ_FSCU&s=kfRCSdaxgM5aBI9y0Hbc-5BJLlhlCki_i3iqyHmOQt8&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAD6ZHZ6VSVIY7V23F3QW732BRWAHAVCNFSM6AAAAABSEKWC72VHI2DSMVQWIX3LMV43ASLTON2WKOZSGY3TKNJRGQ3TIMY&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=xfd3i0lPw8VCmo8bCSyIgn49pfcfLF1wjuN7hntGNPMTIClhVBYJU6fbUsQ_FSCU&s=wOn6Wjg4aAa4PZTPWsym4mAHFT1R24PRNjdG9F25ESQ&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.
