### ISSUE TITLE
GPL-457 As developers we need to modify the creation of samples to reflect the simplified scenario for creating ONT samples

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#362]
**User story**
As developers we need to modify the creation of samples to reflect the simplified scenario for creating ONT samples

**Who the primary contacts are for this story**
Steve / Harry

**Acceptance criteria**
To be considered successful the solution must allow:
1. A plate will contain 96 wells
2. Each well will contain a single sample
3. Each sample must be pre-tagged with a pre existing PCR tag
4. A sample will only be sequenced once

**Additional context**

**Comment by Chris-Friend** [comment]
In order to support this in the most straightforward way possible, we will make the following changes:
* remove sample request relationship
* In the request factory validate that samples have a valid tag, and assign to them this tag
* In the well factory ensure that each well only has a single sample (retaining flexibility to allow multiple samples in a single well)

Tag validation (that all tags are unique) will now be done on library creation.
