### ISSUE TITLE
GPL-470 Condense ONT warehouse messages down to one large nested message

### ISSUE THREAD

**Issue by sdjm-tessella** [sanger/traction-service#394]
**User story**
When ONT runs are created or updated via the GraphQL v2 API, separate messages are sent to the unified warehouse (MLWH) for every sample contained in each library added to flowcells in the run.  Where there could be 5 flow cells in a run and each could contain a library with 96 samples, this would be 480 messages published for a single run.

Pacbio runs generate a single message with an array of wells and an array of samples in those wells.  ONT runs should do something similar where we nest libraries for a run as an array and each of those nest the samples in that library.

**Who the primary contacts are for this story**
Steve Inglis

**Acceptance criteria**
To be considered successful the solution must allow:
1. The message specification for ONT runs should allow for nested arrays of libraries and samples.
2. The single message should be correctly generated for a run when it is created or updated.

**Comment by stevieing** [comment]
we have locally traction sending messages, unified warehouse receiving these and then writing to it's database. However, the unified warehouse requires oseq_flowcell rows be unique on id_flowcell_lims, which is the same for each request in a sample (as it belongs to the same flowcell). As such posting a message for a run with 3 flowcells, each with 96 samples only generates 3 entries in the oseq_flowcells table (see attached).
Stuart and I propose a solution that instead of sending the flowcell.id for id_flowcell_lims we instead send a concatenation of flowcell.id and request.external_id. This should be unique for all requests. It will require handling a new :concat type in message.rb. Thoughts? How is id_flowcell_lims used? Will changing this for the ont pipeline be undesirable?

It works in PacBio because the model in unified warehouse includes NestedResourceTools instead of SingularResourceTools so the create_or_update method only ever creates new records, and doesn't look for singularity based on the base_resource_key.
It actually destroys old records and recreates them all from the new message.
