### ISSUE TITLE
GPL-773 Support SMRTLink Sample Sheet v10

### ISSUE THREAD

**Issue by BenTopping** [sanger/traction-service#509]
Coupled with Traction UI [PR](https://github.com/sanger/traction-ui/pull/553)

**User story**
As developers we need to fix the errors caused by uploading sample_sheets from traction to the new smrtlink v10 as there is an upgrade planned for 14th December.

**Who are the primary contacts for this story**
Carol / Steve

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] upload a sample sheet to the smrtlink test instance without errors

**Tasks**
Service
- Add ‘Generate HiFi Reads
- Remove 'Generate CCS Data
- Remove  'Sequencing Mode' 
- Add ‘CCS Analysis Output - Include Kinetics Information

**Dependencies**
N/A

**Additional context**
You can access our test instance of smrtlink via this address:
-  https://trac-smrtlink-uat.psd.sanger.ac.uk:8243/sl/run-design

You can download sample sheets from any instance of traction from the pacbio run page:
However taking from production is advised as uat run data may not be complete
-  http://traction.psd.sanger.ac.uk/#/pacbio/runs

**Comment by BenTopping** [comment]
**Email thread with Craig**

Main solution:
System Name: Need addition of ‘Sequel IIe’ as an option in the drop down in Traction run setup.
 
**Within the sample sheet:**
Remove: Sequencing Mode
Remove: Generate CCS Data
 
The above two removals, essentially get replaced by: ‘Generate HiFi Reads’
Options:
1)      If Sequel I or Sequel II system the available values should be: **‘In SMRT Link’** OR ‘Do Not Generate’
2)      If Sequel IIe system the available values should be: ‘In SMRT Link’ OR ‘**On Instrument’** OR ‘Do Not Generate’.
Bold highlight = default value preferred.
 
I’m aware that the Pre-extension time is linked to the current Sequencing mode, if CLR=0  & if CCS=2
 
For now, you could just default the pre-extension to 2 (we can then edit if required).

**Other potential issue**
There is only one other problem I envisage. The plan is to upgrade v9 SMRTLink that is connected to the Sequel I to v10. If we are using this version in the short term I think the ‘Barcode Set’ unique ID may be different on this install. I can’t be certain as I think that server is now in the process of being upgraded to v10, so cannot check it out at the moment.

**Comment by harrietc52** [comment]
Update from Craig:
I have just identified another additional field that is now required (per well on a run) for use with SMRTLink v10 in traction.
 
Due to the on board processing functionality of the new instrument we need the option to be able to include a particular data output when the onboard analysis is used.
 
This option related to CCS Analysis Output - Include Kinetics Information
 
The Tree of Life program have indicated that they require it ON for all their samples.
 
I dug around in the user guide but it was not clear how we should include this. However, downloading a Template Sample sheet does have the option we require (attached) included.
 
Please can we have an option that allows us to select ‘CCS Analysis Output - Include Kinetics Information’  Yes or No as part of the run setup information, this should be included per well position.
 
It should only be used if the system type is Sequel IIe and the following field ‘Generate HiFi Reads’ has ‘On Instrument’ selected.
 
Please let me know if you require any further clarification regarding this field. Sorry for the late notice.

**Comment by harrietc52** [comment]
On Deployment Run

`Pacbio::Well.all.map { |well| well.update!(ccs_analysis_output: '', generate_hifi: "In SMRT Link”) }`

**Comment by harrietc52** [comment]
Changes in both Service and UI to support SMRT Link v10 are:
·  Removed Sequencing Mode from Pacbio Well
·  Removed Generate CCS Data from Pacbio Well
·  Added Generate Hifi Reads fields for Pacbio Well. (Previous data is back populated with “In SMRT Link”)
if System Name is "Sequel I" or "Sequel II", options are "In SMRT Link" and "Do Not Generate"
if System Name is "Sequel IIe", options are above as well as "On Instrument"
(Bold are the default values)
·  Added the default “2” to Pre Extension Time for Pacbio Well
·  Added "Sequel IIe" to System Name for Pacbio Run
·  Updated the Sample Sheet
·  Added CCS Analysis Output, options are Yes or No (Previous data is back populated with No)
