### ISSUE TITLE
DPL-281 - ONT - Create a Sequencing Run

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-service#713]
**User story**
One or more pools will be added to a Sequencing run which will be made up of one or more flowcells on either the GridIon or Promethion

**Who are the primary contacts for this story**
Steve / James

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Modify existing Flowcell model to use pool rather than library and track flowcell barcode
- [x] Move instrument name to be a relationship
- [x] Addition of Instrument for tracking purposes
- [x] Modify ONT runs to perist experiment name, add instrument name
- [x] Limiting of maximum flowcells based on instrument

**References**
This story has a relationship with sanger/traction-ui#708

**Additional context**

**Comment by stevieing** [comment]
- [ ] Create flowcell model (include flowcell barcode and position) and add relationship to pool
- [ ] Create instrument model. Options will be; minion - 1 max flowcell, GridIon - 5 max flowcells, Promethion - 24 max flowcells. Need an accompanying rake task to create instruments.
- [ ] Modify run model to persist experiment name and then add instrument relationship. Need a check to ensure that the run has the correct number of flowcells for the instrument

To be continued ...

**Comment by yoldas** [comment]
Attached a simple UI-Service AD for creating run and flowcells.
<img width="944" alt="Screenshot 2023-01-03 at 11 29 48" src="https://user-images.githubusercontent.com/91894/210348925-480ec2af-834b-4b09-bfdb-32d216837668.png">

**Comment by yoldas** [comment]
Added info about ONT Instruments (received by email)

**Instrument Type:**
Strictly, the type names should be MinION, GridION or PromethION, if
they are mixed-case (that's what ONT call them).

**Instrument Name:**
These are also the instrument host names for PromethION and GridION
(they are essentially enhanced Linux boxes). MinIONs are just USB
devices, so don't have an instrument name as such.

**Max Number of Flowcells:**
MinION is always 1.
GridION is always 5.
PromethION is 24 or 48, depending on the model. The one we have at the
moment is 24. (ONT also sell a PromethION P2 with 2 flowcells, but we
don't have one).

**Additional info:**
The flowcells in a GridION are arranged in a row and for customers e.g.
via the ML warehouse, we address them in sequence 1-5 (i.e. 1-based
indexing).

The flowcells on a PromethION are arranged in a grid, but we still allow
addressing them in sequence 1-24 for customers (i.e. 1-based indexing,
in column-major order).

Here's some of our code for parsing the report JSON generated by
PromethION runs which shows this explicitly:
https://github.com/wtsi-npg/valet/blob/devel/valet/report.go 

The instrument name for the current GridION is GXB02004 and the current
PromethION is PC24B148.

MinIONs don't have instrument names because they are just USB devices -
I haven't seen a MinION run for years, so I'm afraid that I can't tell
you if there is a logical equivalent that you can use instead.

**Comment by yoldas** [comment]
Added the snapshot of old Run states dropdown.

<img width="204" alt="Screenshot 2023-01-06 at 10 33 40" src="https://user-images.githubusercontent.com/91894/210994614-fe5712fc-59db-40ce-84cd-b7cee39913ca.png">

**Comment by yoldas** [comment]
Attached a file to show request examples.
[request_examples.txt](https://github.com/sanger/traction-service/files/10369508/request_examples.txt)

**Comment by yoldas** [comment]
Copied the remaining tasks from TODO file.

- [x] Update rake to read instrument (name, type, max_number_of_flowcells) config into database
- [x] Add test for update functionality
- [x] Test update requests on the run for flowcells
- [x] Finish testing flowcell_attributes assignment
- [x] Check the run has a min number of flowcell=1 and max no <= instrument.max_num
- [x] For each Flowcell: It has a flowcell id
- [x] Test the position validation for flowcells
- [x] Test the pool uniqueness validation for flowcells
- [ ] Update the enum for ONT Run states and validate (1)

(1) The current run states are pending, started, completed, and cancelled. However, the old traction states were pending, completed, user_terminated, instrument_crashed, and restart. The last task can be worked on once we learn about the run states required.
