### ISSUE TITLE
DPL-642 Publish TOL lab share sample information to the unified warehouse (S=M)

### ISSUE THREAD

**Issue by emrojo** [sanger/traction-service#922]
**User story**
As TOL I want to publish the sample information received into the warehouse so it can be available for reporting.

**Who are the primary contacts for this story**
Stephen Inglis
Eduardo Martin

**Who is the nominated tester for UAT**
TOL

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] The sample information received from the TOL message is accessible in the unified warehouse

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
Just to note the driver for this story is so that the SSR team can use Tableau to report/show/be alerted to new incoming samples being sent to SeqOps.

Currently the SSR team is notified via email with a sample manifests that gets placed on a RT work queue. This will mean a change in the way the SSR team work at least for this workflow.

NB It may be possible to configure Tableau to automatically send email notifications itself - see https://help.tableau.com/current/pro/desktop/en-us/data_alerts.htm
